schema_version: 1

context:
  python_min: "3.11"
  version: "0.9.9"

package:
  name: fremor
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fremor/fremor-${{ version }}.tar.gz
  sha256: 6cc25ee6d9bfa2ecbe73f379746b9ee718cf71276cf10c12bf574cd4dd96e121

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fremor = fremor.cli:fremor

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - cmor
    - netcdf4
    - numpy
    - pyyaml
    - textual

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - fremor
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - fremor --help
      - fremor --version

about:
  summary: Model output rewriter (CMORizer) for FRE/FMS based models
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://pypi.org/project/fremor/

extra:
  recipe-maintainers:
    - ilaflott
    - fmalatino
